In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels as sm
pd.options.display.max_columns=20
pd.options.display.max_rows=20
pd.options.display.max_colwidth=80
np.set_printoptions(precision=4,suppress=True)

In [ ]:
######################################################### Armazenamento e carregamento dos arrays

In [213]:
print(np.__version__)

1.26.4


In [34]:
#  Armazenamento e carregamento de dados 

objeto1=np.arange(10)   # Criação de um array vetorial com uma sequencia de 0 até 9
objeto2=np.arange(20)   # Criação de uma array vetorial com uma sequencia de 0 até 19

np.save("nome_do_arquivo.npy", objeto1)   # Salval um único arquivo


In [37]:
np.save("arquivo_mais_objetos.npy", objeto1, objeto2)  # Salvando mais de um objeto por arquivo

In [39]:
np.savez_compressed("arq_compactado.npz",objeto1)  # Salvando os arquivos compactados

In [40]:
# Carregamento dos dados numpy

np.load("arq_compactado.npz",arr1)

NpzFile 'arq_compactado.npz' with keys: arr_0

In [41]:
arr1



array([6. , 7.5, 8. , 0. , 1. ])

In [216]:
####################################################### Parametros de um array

print(arr.ndim)
print(arr.shape)

2
(2, 3)


In [ ]:
#######################################################  Criação dos arrays

In [45]:
# Criação de um array de zeros
mat_zeros = np.zeros((5,5))

In [47]:
# Criação de um array de uns
mat_uns = np.ones((7,7))

In [48]:
# Funcionamento do like no ones e zeros

np.ones_like(mat_uns) # Criou um matriz de zeros de mesma dimensão que a matriz de zeros que foi passada como parâmetros

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [49]:
np.zeros_like(mat_zeros) # Criou um matriz de zeros de mesma dimensão que a matriz de zeros que foi passada como parâmetros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
# Criação de espaço na memórioa sem preenchimento com os valors

np.empty_like(mat_zeros)  # Criação da matriz com dimensões iguais a mat_zeros, mas sem passagem de parâmetro

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
np.empty((3,3))   # Alocação de espaço em memória para matriz (3,3) (Não preenche com valor)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# Criação de uma matriz identidade
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
np.identity(8)    # Criação de uma matriz identidade de tamanho 8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [62]:
# Criação de uma matriz com um tipo específico herdando a dimensão de outro array
np.full_like(mat_uns,np.NaN)

array([[nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan]])

In [65]:
# Criação de um array com tamanho e tipo especifico
np.full((4,4),np.inf)

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [220]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
  for y in x:
    print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [67]:
##########################################################  Casting e definição de tipo de dados do array

arr=np.array(range(10)) # Criando um array p/ servir de exemplo

In [69]:
type(arr)   # Tipo do objeto


numpy.ndarray

In [70]:
arr.dtype # Tipo do dado armazenado no objeto

dtype('int32')

In [ ]:
# Fazendo o casting de uma string para numero

In [75]:
arr.dtype

dtype('uint8')

In [76]:
arr = arr.astype(np.uint8) # Casting do int32 para unsigned de 8 - isto impossibilita o registro de nº negativos e esta limitado até 255

# TIPO                Código do tipo
# int8, uint8         i1,u1
# int16, uint16       i2,u2
# int32, uint32       i4,u4
# int64, uint64       i8,u8

# float16              f2
# float32              f4 ou f
# float64              f8 ou d
# float124             f16 ou g

# complex64            c8
# complex128           c16
# complex256           c32

# bool                 ?
# object               O
# string_              S
# unicode_             U



In [77]:
# Fazendo o casting de um array string para float
arr=np.array(["1.0", "2.2", "3.3", ".4", "5.2"])

In [78]:
arr

array(['1.0', '2.2', '3.3', '.4', '5.2'], dtype='<U3')

In [80]:
arr = arr.astype(float)                                              # Fazendo a coversão de string --> float

In [82]:
arr.dtype


dtype('float64')

In [88]:
 # Outro exemplo de casting usando o tipo de referência de outro objeto 

arr2=np.array(["2.4", "5.8", "0.3", "-8.4", "-35.2"])

In [89]:
arr2

array(['2.4', '5.8', '0.3', '-8.4', '-35.2'], dtype='<U5')

In [91]:
arr2.astype(arr.dtype)

array([  2.4,   5.8,   0.3,  -8.4, -35.2])

In [202]:
############################################################  Aritmética com arrays

arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [203]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [204]:
# Adiação de um escalar ao array
arr+10

array([[11., 12., 13.],
       [14., 15., 16.]])

In [205]:
# Multiplicação de um escalar 

arr*3.12

array([[ 3.12,  6.24,  9.36],
       [12.48, 15.6 , 18.72]])

In [206]:
# Multiplicação de número na mesma posição
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [207]:
# Subtração de um array por outro array em uma mesma posição
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [208]:
# Comparações entre arrays de mesma dimensão ( Arrays de tamanho diferentes exigem broadcasting)

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [209]:

arr > np.array([[1,1,1],[6,5,4]])

array([[False,  True,  True],
       [False, False,  True]])

In [211]:
# Multiplicação de matriz

 np.dot(arr,arr.T)

# arr @ arr.T

array([[14., 32.],
       [32., 77.]])

In [212]:
print(arr)
arr.swapaxes(0,1)    # Troca dos eixos selecionados

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [178]:
############################################################# INDEXAÇÃO E FATIAMENTO (SLICING)

arr = np.array(range(16)).reshape(4,4)     # Criando uma sequencia vetorial e transformando a forma para bidimensional 4x4


In [179]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [180]:
arr.shape

(4, 4)

In [181]:
arr.ndim

2

In [182]:
arr[:,0]                                    # Seleção da primeira coluna

array([ 0,  4,  8, 12])

In [183]:
arr[2,:]                                    # Seleção da terceira linha

array([ 8,  9, 10, 11])

In [184]:
arr[1:3,:]                                 # Seleção das linhas 1 e 2 com toda as colunas

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
arr_fatia = arr[1:3,:].copy()               # Fazendo uma copia de uma seleção do array

In [186]:
arr_fatia

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [217]:
# Fatiamento com pulo
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [187]:
 # Indexação booleana

names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
data=np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])
print("Arrayd com os names (string)")
print(names)
print("\nArray com os dados")
print(data)

Arrayd com os names (string)
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Array com os dados
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [188]:
data[names=="Bob",0]                        # Seleção  no array data da primeira colunas onde names==Bob 

array([4, 0])

In [189]:
data[names != "Bob"]                        # Seleção excluindo "Bob"
# data[~(names=="Bob")]                     # Faz a mesma seleção com outra sintaxe

#mask =(names=="Bob")|(names=="Will")       # Seleção com uma condicional combinada
#data[mask] 

# !!!!!!!!!!!!  A seleção de dados por indexação booleana e a atribuição do resultado sempre cria uma cópia dos dados mesmo se o array não for alterado !!!

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [190]:
# Imputação com base em condições boolenas  (similar ao r)
print(data)
data[data[:,0]<0,0] = 0 
print("\nTruncamento dos valores negativos da segunda coluna\n")
print(data)

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]

Truncamento dos valores negativos da segunda coluna

[[ 4  7]
 [ 0  2]
 [ 0  6]
 [ 0  0]
 [ 1  2]
 [ 0 -4]
 [ 3  4]]


In [191]:
data.shape

(7, 2)

In [198]:
# Exemplo de indexação mais sofisticada

arr=np.arange(32).reshape((8,4))
print(arr)
print("\n\n")

arr[[1,5,7,2]][:,[0,3,1,2]]    # A primeira parte seleciona as linhas e a últma seleciona a ordem de apresentação das colunas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]





array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [200]:
# Transposição de um array

arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [221]:
#  nditer possibilita iterar por cada valor do array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [222]:
# Fazendo a iteração com diferentes tamanhos de passo.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [223]:
# ndenumerate mencionar a sequência numérica

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [234]:
#######################################   Manipulando arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [238]:
# Pode fazer a concatenação por linha(axis=0) ou por coluna(axis=1). (similar ao bind_rows, bind_col no R)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [239]:
 # Stack esta mais próximo de cbind ou rbind no r.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [242]:
# hstack faz o empilhamento ao longo da linha  "h" e o vstack faz o empilhamento vertical, e o "d" dstack faz o empilhamento em dimensões (imagens rgb??)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

arr = np.vstack((arr1, arr2))
print(arr)

arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [244]:
# array_split para dividir arrays, passamos o array que queremos dividir e o número de divisões

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [245]:
 # Dividindo uma matriz com escolha do eixo ( coluna)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [247]:
# hsplit()  é usado  para dividir a matriz 2-D em três matrizes 2-D ao longo das linhas.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [248]:
###############################################################  Funcionalidades de BUSCA

# Retorno dos indices em que condição foi verdadeira
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [250]:
# Seleção dos indices com ocorrencia de pares

arr = np.array([1, 2, 3, 4, 5, 6, 10, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 6, 7], dtype=int64),)


In [258]:
# Se cond=True seleciona o elemento do primeiro vetor senão do 2 vetor 

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.4])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result=np.where(cond,xarr,yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [254]:
# realiza uma busca binária na matriz e retorna o índice onde o valor especificado seria inserido para manter a ordem da busca

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')
print(x)

x = np.searchsorted(arr, 7, side='left')
print(x)

2
1


In [255]:
# Filtro de array

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [256]:
# Ordenação de array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
