## O que são ufuncs?

ufuncs significa "Funções Universais" e são funções NumPy que operam no ndarray objeto.

## Por que usar ufuncs?

ufuncs são usados ​​para implementar a vetorização no NumPy, o que é muito mais rápido do que iterar sobre elementos.

Eles também fornecem transmissão e métodos adicionais, como redução, acumulação etc., que são muito úteis para computação.
ufuncs também aceita argumentos adicionais, como:

**where** matriz booleana ou condição que define onde as operações devem ocorrer.

**dtype** definindo o tipo de retorno dos elementos.

**out** matriz de saída onde o valor de retorno deve ser copiado.

## O que é vetorização?

A conversão de instruções iterativas em uma operação baseada em vetor é chamada de vetorização.
É mais rápido porque as CPUs modernas são otimizadas para tais operações.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels as sm
pd.options.display.max_columns=20
pd.options.display.max_rows=20
pd.options.display.max_colwidth=80
np.set_printoptions(precision=4,suppress=True)

## Function Arithmetic

In [ ]:
# ufunc binárias
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = [1.2, 1.24, 1.1, 1.3]

print("x=",x)
print("y=",y)
print("z=",z)

print("x+y=", np.add(x, y))                                       # Adição
print("y-x=", np.subtract(y,x))                                   # Subtração
print("y*x=", np.multiply(y,x))                                   # Multiplicação
print("y/x=",np.divide(y,x))                                      # Divisao
print("y^z=",np.power(y, z))                                      # Elevado a potência
print("x%y=",np.mod(y, x))                                        # Resto da divisão
print("x//y=",np.divmod(y, x))                                    # retorna tanto o quociente 1º array, quanto o mod 2º array.
np.absolute(arr)

In [26]:
# ufunc Unárias

arr = np.array([-1, -2, 1, 2, 3, -4])

print( np.absolute(arr))

print(np.fix([-3.1666, 3.6667]))
print(np.around([-3.1666, 3.6667], 2))
print(np.floor([-3.1666, 3.6667, 2.5]))
print(np.ceil([-3.1666, 3.6667, 2.5]))

[1 2 1 2 3 4]
[-3.  3.]
[-3.17  3.67]
[-4.  3.  2.]
[-3.  4.  3.]


In [64]:
# Exponenciação
arr = np.arange(1, 10)

print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))
print(np.sqrt(arr))

[0.     0.6931 1.0986 1.3863 1.6094 1.7918 1.9459 2.0794 2.1972]
[0.     1.     1.585  2.     2.3219 2.585  2.8074 3.     3.1699]
[0.     0.301  0.4771 0.6021 0.699  0.7782 0.8451 0.9031 0.9542]
[   2.7183    7.3891   20.0855   54.5982  148.4132  403.4288 1096.6332
 2980.958  8103.0839]
[1.     1.4142 1.7321 2.     2.2361 2.4495 2.6458 2.8284 3.    ]


In [ ]:
# 

In [36]:
# Produtórios

arr1 = np.array([1, 2, 3, 4])
print(np.prod(arr1))                              # igual ao produtorio do vetor
print(np.cumprod(arr1))                           # Acumulando o produto, neste exemplo serio o fatorial do indice
arr2 = np.array([5, 6, 7, 8])

print(np.prod([arr1, arr2], axis=1))       # Produtório dentro das colunas
print(np.prod([arr1, arr2], axis=0))       # Produtório dentro das linhas

#  Fazendo a diferença - equivalente ao diff no R muito usado em séries temporais

print(np.diff(arr1))
print(np.diff(arr1,n=2))    # Depois de fazer a primeira diferença, calcula outra diferença 

24
[ 1  2  6 24]
[  24 1680]
[ 5 12 21 32]
[1 1 1]
[0 0]


In [104]:
# Somatorio e outras funções estatísticas

arr = np.arange(10)
print(arr)
print("Somatorio=",np.sum(arr))
print("Soma cumulativa=",np.cumsum(arr))
print("Média=",np.mean(arr))
print("Máximo=",np.max(arr))
print("Mínimo=",np.min(arr))
print("Desvio-Padrao=",np.std(arr))
print("Variancia=",np.var(arr))

arr = np.arange(6).reshape(2,3) + 10
print(arr)
print("Menor=",np.argmin(arr,axis=0)) # Os menores valores estão todos na linha 0


[0 1 2 3 4 5 6 7 8 9]
Somatorio= 45
Soma cumulativa= [ 0  1  3  6 10 15 21 28 36 45]
Média= 4.5
Máximo= 9
Mínimo= 0
Desvio-Padrao= 2.8722813232690143
Variancia= 8.25
[[10 11 12]
 [13 14 15]]
Menor= [0 0 0]


In [88]:
########################  Funções de teste 

arr=np.array([np.nan,1,2,4,-5,np.log(0),-6,np.inf])

print(arr)
print("Teste isnan=",np.isnan(arr))
print("Teste isfinite=",np.isfinite(arr))




[ nan   1.   2.   4.  -5. -inf  -6.  inf]
Teste isnan= [ True False False False False False False False]
Teste isfinite= [False  True  True  True  True False  True False]


C:\Users\Xtrategie\AppData\Local\Temp\ipykernel_7884\1383408342.py:3: RuntimeWarning: divide by zero encountered in log
  arr=np.array([np.nan,1,2,4,-5,np.log(0),-6,np.inf])


In [40]:
######################## Operações de conjunto 

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
print(arr)
print("Unique=",np.unique(arr))      # equivalente a unique do r


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

print("Arr1=",arr1)
print("Arr2=",arr2)
print("Uniao=",np.union1d(arr1, arr2))
print("Interseção=",np.intersect1d(arr1, arr2, assume_unique=True))
print("dif(arr1-arr2)",np.setdiff1d(arr1, arr2, assume_unique=True))
print("elementos exclusivos A+B-(AB)",np.setxor1d(arr1, arr2, assume_unique=True))                               # encontrar apenas os valores que NÃO estão presentes em AMBOS os conjuntos


[1 1 1 2 3 4 5 5 6 7]
Unique= [1 2 3 4 5 6 7]
Arr1= [1 2 3 4]
Arr2= [3 4 5 6]
Uniao= [1 2 3 4 5 6]
Interseção= [3 4]
dif(arr1-arr2) [1 2]
elementos exclusivos A+B-(AB) [1 2 5 6]


In [62]:
########################################### Operações Trigonométricas

print("SEN(30º)=",np.round(np.sin(np.pi/6),2))  # Seno de 30º
print("COS(45º)=",np.round(np.cos(np.pi/4),2))  # Coseno de 45º
print("TG(45º)=",np.round(np.tan(np.pi/4),2))  # Tangente de 45º

print("1º para radiano=",np.deg2rad([1]))
print("1 rad para º=",np.rad2deg([1]))

print("arc sin=",np.arcsin([1]))
print("arc sin (pi/2)=",np.sinh(np.pi/2))

print("hipotenusa (2,2)=", np.hypot(2, 2))

SEN(30º)= 0.5
COS(45º)= 0.71
TG(45º)= 1.0
1º para radiano= [0.0175]
1 rad para º= [57.2958]
arc sin= [1.5708]
arc sin (pi/2)= 2.3012989023072947
hipotenusa (2,2)= 2.8284271247461903


In [ ]:
x = np.arcsin(1.0)
x = np.arcsin(arr)

base = 3
perp = 4


