In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels as sm
pd.options.display.max_columns=20
pd.options.display.max_rows=20
pd.options.display.max_colwidth=80
np.set_printoptions(precision=4,suppress=True)

In [ ]:
############################################## Principais funções de algebra linear no Numpy

#diag - retorna um vetor da diagonal de uma matriz quadrada ou a partir de um vetor constroi um matriz quadrada com zeros fora da diagonal
#dot - multiplicação de matrizes
#trace - Calcula a soma dos elementos na diagonal
#det - calcula o determinante de uma matriz
#eig - calcula os autovalores e autovetores de uma matriz quadrada
#inv - calcula a matriz inversa
#pinv - calcula a pseudo inversa de morro-penrose de uma matriz
#qr - Calcula a decomposicao QR
#svd - Calcula a Decomposição de valor singular
#solve - Resolve o sistema linear Ax=b para x, onde A é uma matriz quadrada
#lstsq - Calcula a solução de minimos quadrados para Ax=b

In [4]:
arr=np.arange(15).reshape((3,5))
print(arr)
np.add.accumulate(arr,axis=1)


In [5]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])